x = int(input())
match x:
    case 1: print("O mês de Janeiro é do primeiro trimestre do ano")
    case 2: print("O mês de Fevereiro é do primeiro trimestre do ano")
    case 3: print("O mês de Março é do primeiro trimestre do ano")
    case 4: print("O mês de Abril é do segundo trimestre do ano")
    case 5: print("O mês de Maio é do segundo trimestre do ano")
    case 6: print("O mês de Junho é do segundo trimestre do ano")
    case 7: print("O mês de Julho é do terceiro trimestre do ano")
    case 8: print("O mês de Agosto é do terceiro trimestre do ano")
    case 9: print("O mês de Setembro é do terceiro trimestre do ano")
    case 10: print("O mês de Outubro é do quarto trimestre do ano")
    case 11: print("O mês de Novembro é do quarto trimestre do ano")
    case 12: print("O mês de Dezembro é do quarto trimestre do ano")
    case _: print("Digite um número de 1 a 12")